
GET http://localhost:3000/api/session/finales/13725/75
Content-Type: application/json


###finales ya rendidos
GET http://localhost:3000/api/session/finales-rendidos/13725/75
Content-Type: application/json
